Downgrade to the minimum working elixir/erlang version
lirossarvet/honeylixir pull request #3
Opened 2020-10-03 12:49 UTC by kianmeng

This PR ensures the module will work with Elixir 1.9.x and Erlang/OTP 22.x.

All these commands works without issues.
```
$ asdf install
$ mix deps.get
$ mix compile
$ mix test
```

2020-10-03 15:42 UTC, lirossarvet requested changes
Hey, thanks for you this! Two things:

1. I'd rather leave the `.tool-versions` file alone, but that's a little more personal preference.
2. We'll need to make sure the `.travis` file is testing 1.9 and OTP 22 as well.

2020-10-04 03:34 UTC, kianmeng commented
@lirossarvet Indeed make sense. Travis CI is the proper place to change it.

2020-10-06 03:13 UTC, lirossarvet approved these changes
Thanks for updating Travis!

2020-10-06 03:15 UTC, lirossarvet commented
@kianmeng do you mind updating your branch with the latest `main`?

2020-10-06 11:36 UTC, kianmeng commented
> @kianmeng do you mind updating your branch with the latest `main`?

@lirossarvet 
It's already rebased to the latest `main` branch from `upstream`.

2020-10-09 23:46 UTC, lirossarvet commented
Merged via https://github.com/lirossarvet/honeylixir/commit/c7ec6bc798d4f8dfe0d67fef33750e723a090b4f via apparently a weird workflow, sorry. I am...very new at maintaining something. however! your author email is correct this time.

2020-10-09 23:46 UTC, closed without merging

2020-10-10 10:46 UTC, kianmeng commented
> Merged via [c7ec6bc](https://github.com/lirossarvet/honeylixir/commit/c7ec6bc798d4f8dfe0d67fef33750e723a090b4f) via apparently a weird workflow, sorry. I am...very new at maintaining something. however! your author email is correct this time.

@lirossarvet LGTM!